// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/config.proto

package configpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigService_GetTenantConfig_FullMethodName     = "/vantageedge.config.v1.ConfigService/GetTenantConfig"
	ConfigService_StreamConfigUpdates_FullMethodName = "/vantageedge.config.v1.ConfigService/StreamConfigUpdates"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigService is served by the control plane and consumed by the
// gateway. It replaces the gateway reading tenant/route/origin
// configuration directly out of Postgres: previously every gateway
// process needed its own database credentials just to answer "which route
// matches this request," which is unnecessary blast radius (a compromised
// or misconfigured gateway instance could read/write any table its DB
// user had access to) and couples the gateway's scaling to Postgres
// connection limits. The gateway now only needs a connection to the
// control plane's gRPC port.
type ConfigServiceClient interface {
	// GetTenantConfig returns a tenant's full serving configuration —
	// itself, its active routes, and each route's origin pool — in one
	// round trip, keyed by the subdomain the gateway extracts from the
	// request Host header.
	GetTenantConfig(ctx context.Context, in *GetTenantConfigRequest, opts ...grpc.CallOption) (*TenantConfig, error)
	// StreamConfigUpdates pushes an event whenever a tenant's routes or
	// origins change, so a gateway holding that tenant's config in its local
	// cache can invalidate it immediately instead of waiting out a fixed
	// TTL. The stream carries only tenant IDs (not the changed data itself)
	// — the client re-fetches via GetTenantConfig, keeping this RPC cheap
	// and avoiding a second, divergent representation of the same config.
	StreamConfigUpdates(ctx context.Context, in *StreamConfigUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdateEvent], error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetTenantConfig(ctx context.Context, in *GetTenantConfigRequest, opts ...grpc.CallOption) (*TenantConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantConfig)
	err := c.cc.Invoke(ctx, ConfigService_GetTenantConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) StreamConfigUpdates(ctx context.Context, in *StreamConfigUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdateEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigService_ServiceDesc.Streams[0], ConfigService_StreamConfigUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConfigUpdatesRequest, ConfigUpdateEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigService_StreamConfigUpdatesClient = grpc.ServerStreamingClient[ConfigUpdateEvent]

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
//
// ConfigService is served by the control plane and consumed by the
// gateway. It replaces the gateway reading tenant/route/origin
// configuration directly out of Postgres: previously every gateway
// process needed its own database credentials just to answer "which route
// matches this request," which is unnecessary blast radius (a compromised
// or misconfigured gateway instance could read/write any table its DB
// user had access to) and couples the gateway's scaling to Postgres
// connection limits. The gateway now only needs a connection to the
// control plane's gRPC port.
type ConfigServiceServer interface {
	// GetTenantConfig returns a tenant's full serving configuration —
	// itself, its active routes, and each route's origin pool — in one
	// round trip, keyed by the subdomain the gateway extracts from the
	// request Host header.
	GetTenantConfig(context.Context, *GetTenantConfigRequest) (*TenantConfig, error)
	// StreamConfigUpdates pushes an event whenever a tenant's routes or
	// origins change, so a gateway holding that tenant's config in its local
	// cache can invalidate it immediately instead of waiting out a fixed
	// TTL. The stream carries only tenant IDs (not the changed data itself)
	// — the client re-fetches via GetTenantConfig, keeping this RPC cheap
	// and avoiding a second, divergent representation of the same config.
	StreamConfigUpdates(*StreamConfigUpdatesRequest, grpc.ServerStreamingServer[ConfigUpdateEvent]) error
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) GetTenantConfig(context.Context, *GetTenantConfigRequest) (*TenantConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantConfig not implemented")
}
func (UnimplementedConfigServiceServer) StreamConfigUpdates(*StreamConfigUpdatesRequest, grpc.ServerStreamingServer[ConfigUpdateEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamConfigUpdates not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_GetTenantConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetTenantConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetTenantConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetTenantConfig(ctx, req.(*GetTenantConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_StreamConfigUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConfigUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigServiceServer).StreamConfigUpdates(m, &grpc.GenericServerStream[StreamConfigUpdatesRequest, ConfigUpdateEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigService_StreamConfigUpdatesServer = grpc.ServerStreamingServer[ConfigUpdateEvent]

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vantageedge.config.v1.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTenantConfig",
			Handler:    _ConfigService_GetTenantConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConfigUpdates",
			Handler:       _ConfigService_StreamConfigUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/config.proto",
}
