// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api/proto/config.proto

package configpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTenantConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subdomain     string                 `protobuf:"bytes,1,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantConfigRequest) Reset() {
	*x = GetTenantConfigRequest{}
	mi := &file_api_proto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantConfigRequest) ProtoMessage() {}

func (x *GetTenantConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantConfigRequest.ProtoReflect.Descriptor instead.
func (*GetTenantConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetTenantConfigRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

type StreamConfigUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamConfigUpdatesRequest) Reset() {
	*x = StreamConfigUpdatesRequest{}
	mi := &file_api_proto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfigUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfigUpdatesRequest) ProtoMessage() {}

func (x *StreamConfigUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfigUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamConfigUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{1}
}

type ConfigUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdateEvent) Reset() {
	*x = ConfigUpdateEvent{}
	mi := &file_api_proto_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdateEvent) ProtoMessage() {}

func (x *ConfigUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdateEvent.ProtoReflect.Descriptor instead.
func (*ConfigUpdateEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigUpdateEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type TenantConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Subdomain     string                 `protobuf:"bytes,2,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Routes        []*RouteConfig         `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantConfig) Reset() {
	*x = TenantConfig{}
	mi := &file_api_proto_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantConfig) ProtoMessage() {}

func (x *TenantConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantConfig.ProtoReflect.Descriptor instead.
func (*TenantConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{3}
}

func (x *TenantConfig) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantConfig) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *TenantConfig) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantConfig) GetRoutes() []*RouteConfig {
	if x != nil {
		return x.Routes
	}
	return nil
}

type RouteConfig struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PathPattern                string                 `protobuf:"bytes,3,opt,name=path_pattern,json=pathPattern,proto3" json:"path_pattern,omitempty"`
	Methods                    []string               `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`
	Priority                   int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	AuthMode                   string                 `protobuf:"bytes,6,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`
	RateLimitEnabled           bool                   `protobuf:"varint,7,opt,name=rate_limit_enabled,json=rateLimitEnabled,proto3" json:"rate_limit_enabled,omitempty"`
	RateLimitRequestsPerSecond int32                  `protobuf:"varint,8,opt,name=rate_limit_requests_per_second,json=rateLimitRequestsPerSecond,proto3" json:"rate_limit_requests_per_second,omitempty"`
	RateLimitBurst             int32                  `protobuf:"varint,9,opt,name=rate_limit_burst,json=rateLimitBurst,proto3" json:"rate_limit_burst,omitempty"`
	RateLimitKeyStrategy       string                 `protobuf:"bytes,10,opt,name=rate_limit_key_strategy,json=rateLimitKeyStrategy,proto3" json:"rate_limit_key_strategy,omitempty"`
	CacheEnabled               bool                   `protobuf:"varint,11,opt,name=cache_enabled,json=cacheEnabled,proto3" json:"cache_enabled,omitempty"`
	CacheTtlSeconds            int32                  `protobuf:"varint,12,opt,name=cache_ttl_seconds,json=cacheTtlSeconds,proto3" json:"cache_ttl_seconds,omitempty"`
	CacheKeyPattern            string                 `protobuf:"bytes,13,opt,name=cache_key_pattern,json=cacheKeyPattern,proto3" json:"cache_key_pattern,omitempty"`
	TimeoutSeconds             int32                  `protobuf:"varint,14,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RetryAttempts              int32                  `protobuf:"varint,15,opt,name=retry_attempts,json=retryAttempts,proto3" json:"retry_attempts,omitempty"`
	Origins                    []*OriginConfig        `protobuf:"bytes,16,rep,name=origins,proto3" json:"origins,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RouteConfig) Reset() {
	*x = RouteConfig{}
	mi := &file_api_proto_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConfig) ProtoMessage() {}

func (x *RouteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConfig.ProtoReflect.Descriptor instead.
func (*RouteConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{4}
}

func (x *RouteConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RouteConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RouteConfig) GetPathPattern() string {
	if x != nil {
		return x.PathPattern
	}
	return ""
}

func (x *RouteConfig) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *RouteConfig) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RouteConfig) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

func (x *RouteConfig) GetRateLimitEnabled() bool {
	if x != nil {
		return x.RateLimitEnabled
	}
	return false
}

func (x *RouteConfig) GetRateLimitRequestsPerSecond() int32 {
	if x != nil {
		return x.RateLimitRequestsPerSecond
	}
	return 0
}

func (x *RouteConfig) GetRateLimitBurst() int32 {
	if x != nil {
		return x.RateLimitBurst
	}
	return 0
}

func (x *RouteConfig) GetRateLimitKeyStrategy() string {
	if x != nil {
		return x.RateLimitKeyStrategy
	}
	return ""
}

func (x *RouteConfig) GetCacheEnabled() bool {
	if x != nil {
		return x.CacheEnabled
	}
	return false
}

func (x *RouteConfig) GetCacheTtlSeconds() int32 {
	if x != nil {
		return x.CacheTtlSeconds
	}
	return 0
}

func (x *RouteConfig) GetCacheKeyPattern() string {
	if x != nil {
		return x.CacheKeyPattern
	}
	return ""
}

func (x *RouteConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *RouteConfig) GetRetryAttempts() int32 {
	if x != nil {
		return x.RetryAttempts
	}
	return 0
}

func (x *RouteConfig) GetOrigins() []*OriginConfig {
	if x != nil {
		return x.Origins
	}
	return nil
}

type OriginConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url             string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Weight          int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	TimeoutSeconds  int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	HealthCheckPath string                 `protobuf:"bytes,5,opt,name=health_check_path,json=healthCheckPath,proto3" json:"health_check_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OriginConfig) Reset() {
	*x = OriginConfig{}
	mi := &file_api_proto_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginConfig) ProtoMessage() {}

func (x *OriginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginConfig.ProtoReflect.Descriptor instead.
func (*OriginConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_config_proto_rawDescGZIP(), []int{5}
}

func (x *OriginConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OriginConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *OriginConfig) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *OriginConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *OriginConfig) GetHealthCheckPath() string {
	if x != nil {
		return x.HealthCheckPath
	}
	return ""
}

var File_api_proto_config_proto protoreflect.FileDescriptor

const file_api_proto_config_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/config.proto\x12\x15vantageedge.config.v1\"6\n" +
	"\x16GetTenantConfigRequest\x12\x1c\n" +
	"\tsubdomain\x18\x01 \x01(\tR\tsubdomain\"\x1c\n" +
	"\x1aStreamConfigUpdatesRequest\"0\n" +
	"\x11ConfigUpdateEvent\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\x9d\x01\n" +
	"\fTenantConfig\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1c\n" +
	"\tsubdomain\x18\x02 \x01(\tR\tsubdomain\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12:\n" +
	"\x06routes\x18\x04 \x03(\v2\".vantageedge.config.v1.RouteConfigR\x06routes\"\x86\x05\n" +
	"\vRouteConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fpath_pattern\x18\x03 \x01(\tR\vpathPattern\x12\x18\n" +
	"\amethods\x18\x04 \x03(\tR\amethods\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1b\n" +
	"\tauth_mode\x18\x06 \x01(\tR\bauthMode\x12,\n" +
	"\x12rate_limit_enabled\x18\a \x01(\bR\x10rateLimitEnabled\x12B\n" +
	"\x1erate_limit_requests_per_second\x18\b \x01(\x05R\x1arateLimitRequestsPerSecond\x12(\n" +
	"\x10rate_limit_burst\x18\t \x01(\x05R\x0erateLimitBurst\x125\n" +
	"\x17rate_limit_key_strategy\x18\n" +
	" \x01(\tR\x14rateLimitKeyStrategy\x12#\n" +
	"\rcache_enabled\x18\v \x01(\bR\fcacheEnabled\x12*\n" +
	"\x11cache_ttl_seconds\x18\f \x01(\x05R\x0fcacheTtlSeconds\x12*\n" +
	"\x11cache_key_pattern\x18\r \x01(\tR\x0fcacheKeyPattern\x12'\n" +
	"\x0ftimeout_seconds\x18\x0e \x01(\x05R\x0etimeoutSeconds\x12%\n" +
	"\x0eretry_attempts\x18\x0f \x01(\x05R\rretryAttempts\x12=\n" +
	"\aorigins\x18\x10 \x03(\v2#.vantageedge.config.v1.OriginConfigR\aorigins\"\x9d\x01\n" +
	"\fOriginConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12*\n" +
	"\x11health_check_path\x18\x05 \x01(\tR\x0fhealthCheckPath2\xec\x01\n" +
	"\rConfigService\x12e\n" +
	"\x0fGetTenantConfig\x12-.vantageedge.config.v1.GetTenantConfigRequest\x1a#.vantageedge.config.v1.TenantConfig\x12t\n" +
	"\x13StreamConfigUpdates\x121.vantageedge.config.v1.StreamConfigUpdatesRequest\x1a(.vantageedge.config.v1.ConfigUpdateEvent0\x01B<Z:github.com/vantageedge/backend/api/proto/configpb;configpbb\x06proto3"

var (
	file_api_proto_config_proto_rawDescOnce sync.Once
	file_api_proto_config_proto_rawDescData []byte
)

func file_api_proto_config_proto_rawDescGZIP() []byte {
	file_api_proto_config_proto_rawDescOnce.Do(func() {
		file_api_proto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_config_proto_rawDesc), len(file_api_proto_config_proto_rawDesc)))
	})
	return file_api_proto_config_proto_rawDescData
}

var file_api_proto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_config_proto_goTypes = []any{
	(*GetTenantConfigRequest)(nil),     // 0: vantageedge.config.v1.GetTenantConfigRequest
	(*StreamConfigUpdatesRequest)(nil), // 1: vantageedge.config.v1.StreamConfigUpdatesRequest
	(*ConfigUpdateEvent)(nil),          // 2: vantageedge.config.v1.ConfigUpdateEvent
	(*TenantConfig)(nil),               // 3: vantageedge.config.v1.TenantConfig
	(*RouteConfig)(nil),                // 4: vantageedge.config.v1.RouteConfig
	(*OriginConfig)(nil),               // 5: vantageedge.config.v1.OriginConfig
}
var file_api_proto_config_proto_depIdxs = []int32{
	4, // 0: vantageedge.config.v1.TenantConfig.routes:type_name -> vantageedge.config.v1.RouteConfig
	5, // 1: vantageedge.config.v1.RouteConfig.origins:type_name -> vantageedge.config.v1.OriginConfig
	0, // 2: vantageedge.config.v1.ConfigService.GetTenantConfig:input_type -> vantageedge.config.v1.GetTenantConfigRequest
	1, // 3: vantageedge.config.v1.ConfigService.StreamConfigUpdates:input_type -> vantageedge.config.v1.StreamConfigUpdatesRequest
	3, // 4: vantageedge.config.v1.ConfigService.GetTenantConfig:output_type -> vantageedge.config.v1.TenantConfig
	2, // 5: vantageedge.config.v1.ConfigService.StreamConfigUpdates:output_type -> vantageedge.config.v1.ConfigUpdateEvent
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_config_proto_init() }
func file_api_proto_config_proto_init() {
	if File_api_proto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_config_proto_rawDesc), len(file_api_proto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_config_proto_goTypes,
		DependencyIndexes: file_api_proto_config_proto_depIdxs,
		MessageInfos:      file_api_proto_config_proto_msgTypes,
	}.Build()
	File_api_proto_config_proto = out.File
	file_api_proto_config_proto_goTypes = nil
	file_api_proto_config_proto_depIdxs = nil
}
